// File generated by FlutterFire CLI. Do not modify.
// This file is generated using the FlutterFire CLI based on your Firebase project's settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - ',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnDniIEw2I4caBDtPloQHnx6sKxsdKicY',
    appId: '1:12936307916:web:ca0612b09dfd7aab6f0e69',
    messagingSenderId: '12936307916',
    projectId: 'zameel-activities',
    authDomain: 'zameel-activities.firebaseapp.com',
    databaseURL:
        'https://zameel-activities-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zameel-activities.firebasestorage.app',
    measurementId: 'G-1HZQQT0CH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC32Ypw69HGOQihZjzA_OeHSGkKUb8KHWs',
    appId: '1:12936307916:android:ce53a6a6706e18006f0e69',
    messagingSenderId: '12936307916',
    projectId: 'zameel-activities',
    databaseURL:
        'https://zameel-activities-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zameel-activities.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo14TBSenlcK7hGy-9He5c-D-UDVitHd8',
    appId: '1:12936307916:ios:88c33eb53c2dc7066f0e69',
    messagingSenderId: '12936307916',
    projectId: 'zameel-activities',
    databaseURL:
        'https://zameel-activities-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zameel-activities.firebasestorage.app',
    androidClientId:
        '12936307916-h4rdgs0fmfb7h049ong7ssn0ng4nsq9q.apps.googleusercontent.com',
    iosClientId:
        '12936307916-pmfnkunfjpjpdvggk1ohmsv8q1dp84sf.apps.googleusercontent.com',
    iosBundleId: 'org.wisdom.zameelactivities',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo14TBSenlcK7hGy-9He5c-D-UDVitHd8',
    appId: '1:12936307916:ios:1a450733ad9285876f0e69',
    messagingSenderId: '12936307916',
    projectId: 'zameel-activities',
    databaseURL:
        'https://zameel-activities-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zameel-activities.firebasestorage.app',
    androidClientId:
        '12936307916-h4rdgs0fmfb7h049ong7ssn0ng4nsq9q.apps.googleusercontent.com',
    iosClientId:
        '12936307916-cqgpdkpej2g3ccodke4onmpj25p3c2vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.basic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnDniIEw2I4caBDtPloQHnx6sKxsdKicY',
    appId: '1:12936307916:web:ed3d4d1eedca07686f0e69',
    messagingSenderId: '12936307916',
    projectId: 'zameel-activities',
    authDomain: 'zameel-activities.firebaseapp.com',
    databaseURL:
        'https://zameel-activities-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zameel-activities.firebasestorage.app',
    measurementId: 'G-8GF2KZCLXE',
  );
}
